#!/usr/bin/env python3
"""Regenerate the table of contents at the top of `README.md`.

Why this exists
---------------
`README.md` is ~2,600 lines and carries 33 `##` sections, thirteen of them
milestone status write-ups **in the order they were written, not numeric
order**: M12/13, M14, M7, M15, M6, M5, M16, M17, M18, M8, M9, M10, M19. The
file's own `## Finding things` section admits it and tells the reader to grep.

A wholesale reorder was proposed, approved, and then *reversed*
(`Reports/documentation-overhaul-plan.md` item 11): agents navigate by grep,
the reorder is a huge diff on a contested file, and "a TOC buys the same
navigation for 3% of the churn". The status sections that item asked for
landed; the TOC did not. This is that TOC, so this script is the unexecuted
half of an approved item rather than a new proposal -- do not read it as an
argument for reordering, which stays refused.

Two audiences, one table: the **anchor** is for a human reading on GitHub, the
**line number** for an agent that is going to `sed -n '1351,1400p'`. The
milestone index below it is sorted numerically, which is the one thing grep
cannot do for you.

Sibling of `scripts/bugindex.py`, and shares its two hard-won mechanics: the
line numbers cite a document the table is inside, so generation iterates to a
fixpoint; and the block is *derived*, so a merge conflict inside it is never
hand-merged -- take either side whole and re-run.

Regenerate with `python3 scripts/readmetoc.py`; `--check` verifies it is
current and is what `scripts/docscheck.sh` runs.
"""

import re
import sys
from pathlib import Path

DOC = Path(__file__).resolve().parent.parent / "README.md"
BEGIN = "<!-- BEGIN GENERATED TOC -- regenerate with scripts/readmetoc.py -->"
END = "<!-- END GENERATED TOC -->"


def anchor(title):
    """GitHub's heading-anchor rule: lowercase, drop punctuation, spaces to
    hyphens. An em dash surrounded by spaces therefore yields a double hyphen,
    which is correct and looks like a typo."""
    a = title.lower()
    a = re.sub(r"[^a-z0-9 \-]", "", a)
    return a.replace(" ", "-")


def headings(lines):
    """Every `##` heading, skipping the generated block and fenced code.

    Without the first skip the table lists its own `## Contents` heading and
    points at itself -- harmless, but it makes the section count wrong and the
    fixpoint one iteration slower. The second skip is pre-emptive: no fenced
    block in `README.md` currently starts a line with `## `, but a shell
    transcript or a markdown example easily could, and the failure would be a
    confident index entry pointing at a line that is not a section.
    """
    inside = False
    fenced = False
    for i, line in enumerate(lines, 1):
        if line.startswith("```"):
            fenced = not fenced
            continue
        if line.startswith(BEGIN):
            inside = True
        elif line.startswith(END):
            inside = False
        elif not inside and not fenced and line.startswith("## "):
            yield line[3:].strip(), i


def milestone_key(title):
    """Sort key for `M<n> ...` headings. `M12/M13` sorts on 12."""
    m = re.match(r"M(\d+)", title)
    return int(m.group(1)) if m else None


def render(rows):
    out = [
        BEGIN,
        "",
        "## Contents",
        "",
        f"Generated by `scripts/readmetoc.py` from the `##` headings — {len(rows)} of",
        "them. The **anchor** is for reading on GitHub; the **line** is for jumping",
        "with `sed -n`. Sections sit in the order they were written; that is",
        "deliberate and a reorder was considered and refused",
        "(`Reports/documentation-overhaul-plan.md` item 11), so this table is how",
        "you navigate instead.",
        "",
        "**Merge conflict in this block?** Do not hand-merge it. Take either side",
        "whole, then run `python3 scripts/readmetoc.py`.",
        "",
        "| Section | Line |",
        "|---|---|",
    ]
    for title, line in rows:
        out.append(f"| [{title}](#{anchor(title)}) | {line} |")

    ms = sorted(
        ((milestone_key(t), t, l) for t, l in rows if milestone_key(t) is not None),
        key=lambda r: r[0],
    )
    if ms:
        out += [
            "",
            "### Milestones, in numeric order",
            "",
            "The one ordering grep cannot give you: these sit in the file in the",
            "order they were written.",
            "",
            "| M | Section | Line |",
            "|---|---|---|",
        ]
        for n, title, line in ms:
            out.append(f"| {n} | [{title}](#{anchor(title)}) | {line} |")
    out += ["", END]
    return "\n".join(out)


def splice(text, block):
    if BEGIN in text:
        return text[: text.index(BEGIN)] + block + text[text.index(END) + len(END) :]
    anchor_at = text.index("\n## ")
    return text[:anchor_at] + "\n" + block + "\n" + text[anchor_at:]


def build(text):
    updated = text
    for _ in range(5):
        candidate = splice(updated, render(list(headings(updated.split("\n")))))
        if candidate == updated:
            return candidate
        updated = candidate
    raise SystemExit("readmetoc: did not converge -- line numbering is unstable")


def main():
    args = set(sys.argv[1:])
    unknown = args - {"--check"}
    if unknown:
        print(f"readmetoc: unrecognised argument(s): {' '.join(sorted(unknown))}")
        print("usage: readmetoc.py [--check]")
        return 2
    with open(DOC, encoding="utf-8", newline="") as fh:
        text = fh.read()
    updated = build(text)
    if "--check" in args:
        if updated != text:
            print("readmetoc: README.md table of contents is stale -- run `python3 scripts/readmetoc.py`")
            return 1
        print("readmetoc: table of contents current")
        return 0
    with open(DOC, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(updated)
    print(f"readmetoc: wrote {len(list(headings(updated.split(chr(10)))))} sections")
    return 0


if __name__ == "__main__":
    sys.exit(main())
